<a href="https://colab.research.google.com/github/2303A52413/STAT_2303A52413/blob/main/STML_Assignment_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import Perceptron
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [ ]:
d = pd.read_csv('/content/breast_cancer_survival.csv')
print(d.head())
print(d.tail())
print(d.describe())

   Age  Gender  Protein1  Protein2  Protein3  Protein4 Tumour_Stage  \
0   42  FEMALE   0.95256   2.15000  0.007972 -0.048340           II   
1   54  FEMALE   0.00000   1.38020 -0.498030 -0.507320           II   
2   63  FEMALE  -0.52303   1.76400 -0.370190  0.010815           II   
3   78  FEMALE  -0.87618   0.12943 -0.370380  0.132190            I   
4   42  FEMALE   0.22611   1.74910 -0.543970 -0.390210           II   

                       Histology ER status PR status HER2 status Surgery_type  \
0  Infiltrating Ductal Carcinoma  Positive  Positive    Negative        Other   
1  Infiltrating Ductal Carcinoma  Positive  Positive    Negative        Other   
2  Infiltrating Ductal Carcinoma  Positive  Positive    Negative   Lumpectomy   
3  Infiltrating Ductal Carcinoma  Positive  Positive    Negative        Other   
4  Infiltrating Ductal Carcinoma  Positive  Positive    Positive   Lumpectomy   

  Date_of_Surgery Date_of_Last_Visit Patient_Status  
0       20-May-18          26-Au

In [ ]:
d.head()

Age  Gender  Protein1  Protein2  Protein3  Protein4 Tumour_Stage  \
0   42  FEMALE   0.95256   2.15000  0.007972 -0.048340           II   
1   54  FEMALE   0.00000   1.38020 -0.498030 -0.507320           II   
2   63  FEMALE  -0.52303   1.76400 -0.370190  0.010815           II   
3   78  FEMALE  -0.87618   0.12943 -0.370380  0.132190            I   
4   42  FEMALE   0.22611   1.74910 -0.543970 -0.390210           II   

                       Histology ER status PR status HER2 status Surgery_type  \
0  Infiltrating Ductal Carcinoma  Positive  Positive    Negative        Other   
1  Infiltrating Ductal Carcinoma  Positive  Positive    Negative        Other   
2  Infiltrating Ductal Carcinoma  Positive  Positive    Negative   Lumpectomy   
3  Infiltrating Ductal Carcinoma  Positive  Positive    Negative        Other   
4  Infiltrating Ductal Carcinoma  Positive  Positive    Positive   Lumpectomy   

  Date_of_Surgery Date_of_Last_Visit Patient_Status  
0       20-May-18          26-Aug-18          Alive  
1       26-Apr-18          25-Jan-19           Dead  
2       24-Aug-18          08-Apr-20          Alive  
3       16-Nov-18          28-Jul-20          Alive  
4       12-Dec-18          05-Jan-19          Alive

In [ ]:
y = d['Patient_Status']
x = d.drop(['Date_of_Surgery', 'Date_of_Last_Visit', 'Patient_Status'], axis=1)
print("Target: ", y)
print("Features: ", x)

Target:  0      Alive
1       Dead
2      Alive
3      Alive
4      Alive
       ...  
329    Alive
330    Alive
331     Dead
332    Alive
333     Dead
Name: Patient_Status, Length: 334, dtype: object
Features:       Age  Gender  Protein1  Protein2  Protein3  Protein4 Tumour_Stage  \
0     42  FEMALE  0.952560   2.15000  0.007972 -0.048340           II   
1     54  FEMALE  0.000000   1.38020 -0.498030 -0.507320           II   
2     63  FEMALE -0.523030   1.76400 -0.370190  0.010815           II   
3     78  FEMALE -0.876180   0.12943 -0.370380  0.132190            I   
4     42  FEMALE  0.226110   1.74910 -0.543970 -0.390210           II   
..   ...     ...       ...       ...       ...       ...          ...   
329   59  FEMALE  0.024598   1.40050  0.024751  0.280320           II   
330   41  FEMALE  0.100120  -0.46547  0.472370 -0.523870            I   
331   54  FEMALE  0.753820   1.64250 -0.332850  0.857860           II   
332   74  FEMALE  0.972510   1.42680 -0.366570 -0.107820  

In [ ]:
x = x.replace({'Gender': {'MALE': 0, 'FEMALE': 1}})
x = x.replace({'Tumour_Stage': {'I': 1, 'II': 2, 'III': 3}})
x = x.replace({'Histology': {'Infiltrating Ductal Carcinoma': 1, 'Infiltrating Lobular Carcinoma': 2, 'Mucinous Carcinoma': 3}})
x = x.replace({'Surgery_type': {'Other': 1, 'Lumpectomy': 2, 'Modified Radical Mastectomy': 3, 'Simple Mastectomy': 4}})
x = x.replace({'ER status': {'Positive': 1, 'Negative': 0}})
x = x.replace({'PR status': {'Positive': 1, 'Negative': 0}})
x = x.replace({'HER2 status': {'Positive': 1, 'Negative': 0}})
y = y.replace({'Alive': 0, 'Dead': 1})
print(x)
print(y)

     Age  Gender  Protein1  Protein2  Protein3  Protein4  Tumour_Stage  \
0     42       1  0.952560   2.15000  0.007972 -0.048340             2   
1     54       1  0.000000   1.38020 -0.498030 -0.507320             2   
2     63       1 -0.523030   1.76400 -0.370190  0.010815             2   
3     78       1 -0.876180   0.12943 -0.370380  0.132190             1   
4     42       1  0.226110   1.74910 -0.543970 -0.390210             2   
..   ...     ...       ...       ...       ...       ...           ...   
329   59       1  0.024598   1.40050  0.024751  0.280320             2   
330   41       1  0.100120  -0.46547  0.472370 -0.523870             1   
331   54       1  0.753820   1.64250 -0.332850  0.857860             2   
332   74       1  0.972510   1.42680 -0.366570 -0.107820             2   
333   66       1  0.286380   1.39980  0.318830  0.836050             2   

     Histology  ER status  PR status  HER2 status  Surgery_type  
0            1          1          1         

In [ ]:
x = (x - x.min()) / (x.max() - x.min())
x.fillna(0, inplace=True)
y.fillna(0, inplace=True)
print("Normalized Features:", x)
print("Normalized Features:", y)

Normalized Features:           Age  Gender  Protein1  Protein2  Protein3  Protein4  Tumour_Stage  \
0    0.213115     1.0  0.837072  0.714170  0.428018  0.540887           0.5   
1    0.409836     1.0  0.594968  0.538454  0.295585  0.415325           0.5   
2    0.557377     1.0  0.462033  0.626061  0.329044  0.557070           0.5   
3    0.803279     1.0  0.372276  0.252951  0.328994  0.590275           0.0   
4    0.213115     1.0  0.652436  0.622660  0.283561  0.447363           0.5   
..        ...     ...       ...       ...       ...       ...           ...   
329  0.491803     1.0  0.601219  0.543088  0.432410  0.630798           0.5   
330  0.196721     1.0  0.620414  0.117158  0.549563  0.410798           0.0   
331  0.409836     1.0  0.786560  0.598327  0.338816  0.788795           0.5   
332  0.737705     1.0  0.842143  0.549091  0.329991  0.524616           0.5   
333  0.606557     1.0  0.667754  0.542928  0.509378  0.782828           0.5   

     Histology  ER status  PR 

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print("Training Features:", x_train)
print("Training Target:", y_train)
print("Testing Features:", x_test)
print("Testing Target:", y_test)

Training Features:           Age  Gender  Protein1  Protein2  Protein3  Protein4  Tumour_Stage  \
224  0.147541     1.0  0.526738  0.267952  0.157742  0.581939           1.0   
78   0.786885     1.0  0.519049  0.186591  0.546514  0.445598           0.5   
295  0.295082     1.0  0.546662  0.674886  0.423939  0.563776           0.5   
17   0.557377     1.0  0.608369  0.388235  0.345150  0.408768           1.0   
24   0.672131     1.0  0.772955  0.445613  0.348343  0.582976           0.0   
..        ...     ...       ...       ...       ...       ...           ...   
188  0.245902     1.0  0.524097  0.718462  0.304928  0.628577           0.5   
71   0.262295     1.0  0.414098  0.609718  0.216353  0.771434           0.5   
106  0.327869     1.0  0.610635  0.523549  0.399928  0.760494           0.5   
270  0.819672     1.0  0.472286  0.151100  0.549356  0.649160           0.5   
102  0.491803     1.0  0.686247  0.493943  0.315094  0.667900           0.5   

     Histology  ER status  PR st

Using SVM

In [ ]:
model = SVC()
test_size = 0.312
x_train, x_test, y_train, y_test = train_test_split(
      x, y, test_size=test_size, random_state=58
  )
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy with test size {test_size}: {accuracy}")
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_mat)
classification_rep = classification_report(y_test, y_pred, zero_division=1)
print("Classification Report:")
print(classification_rep)

Accuracy with test size 0.312: 0.8380952380952381
Confusion Matrix:
[[88  0]
 [17  0]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.84      1.00      0.91        88
         1.0       1.00      0.00      0.00        17

    accuracy                           0.84       105
   macro avg       0.92      0.50      0.46       105
weighted avg       0.86      0.84      0.76       105



Using Logistic Regression

In [ ]:
test_size_ranges = [0.2, 0.25, 0.3, 0.35]
for test_size in test_size_ranges:
  x_train, x_test, y_train, y_test = train_test_split(
      x, y, test_size=test_size, random_state=58
  )
  model = LogisticRegression()
  model.fit(x_train, y_train)
  y_pred = model.predict(x_test)
  accuracy = accuracy_score(y_test, y_pred)
  print(f"Accuracy with test size {test_size}: {accuracy}")
  confusion_mat = confusion_matrix(y_test, y_pred)
  print("Confusion Matrix:")
  print(confusion_mat)
  classification_rep = classification_report(y_test, y_pred, zero_division=1)
  print("Classification Report:")
  print(classification_rep)

Accuracy with test size 0.2: 0.8059701492537313
Confusion Matrix:
[[54  0]
 [13  0]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.81      1.00      0.89        54
         1.0       1.00      0.00      0.00        13

    accuracy                           0.81        67
   macro avg       0.90      0.50      0.45        67
weighted avg       0.84      0.81      0.72        67

Accuracy with test size 0.25: 0.8214285714285714
Confusion Matrix:
[[69  0]
 [15  0]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.82      1.00      0.90        69
         1.0       1.00      0.00      0.00        15

    accuracy                           0.82        84
   macro avg       0.91      0.50      0.45        84
weighted avg       0.85      0.82      0.74        84

Accuracy with test size 0.3: 0.8316831683168316
Confusion Matrix:
[[84  0]
 [17  0]]
Classification Report:
              precisi